package vista;

import controlador.GestionRol;
import java.awt.Color;
import modelo.Rol;

public class AltaCliente extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public AltaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolAlta = new javax.swing.JPanel();
        lblNombreRolAlta = new javax.swing.JLabel();
        lblDescripcionRolAlta = new javax.swing.JLabel();
        txtNombreRolAlta = new javax.swing.JTextField();
        btnRegistrarRolAlta = new javax.swing.JButton();
        lblDescripcionRolAlta1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblNombreRolAlta1 = new javax.swing.JLabel();
        txtNombreRolAlta1 = new javax.swing.JTextField();
        lblNombreRolAlta2 = new javax.swing.JLabel();
        txtNombreRolAlta2 = new javax.swing.JTextField();
        lblTituloRolAlta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolAlta.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolAlta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolAlta.setOpaque(false);

        lblNombreRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta.setText("Razón Social");

        lblDescripcionRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolAlta.setText("Teléfono");

        btnRegistrarRolAlta.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarRolAlta.setText("Registrar");
        btnRegistrarRolAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRolAltaActionPerformed(evt);
            }
        });

        lblDescripcionRolAlta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolAlta1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolAlta1.setText("RFC");

        lblNombreRolAlta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta1.setText("Dirección");

        lblNombreRolAlta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta2.setText("e-mail");

        javax.swing.GroupLayout panDatosRolAltaLayout = new javax.swing.GroupLayout(panDatosRolAlta);
        panDatosRolAlta.setLayout(panDatosRolAltaLayout);
        panDatosRolAltaLayout.setHorizontalGroup(
            panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                        .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosRolAltaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegistrarRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211))
                            .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                                    .addComponent(lblNombreRolAlta2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreRolAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                                    .addComponent(lblNombreRolAlta1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreRolAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                                    .addComponent(lblDescripcionRolAlta1)
                                    .addGap(41, 41, 41)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblDescripcionRolAlta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                        .addComponent(lblNombreRolAlta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(txtNombreRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        panDatosRolAltaLayout.setVerticalGroup(
            panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRolAlta))
                .addGap(48, 48, 48)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionRolAlta)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionRolAlta1))
                .addGap(61, 61, 61)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRolAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRolAlta1))
                .addGap(52, 52, 52)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRolAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRolAlta2))
                .addGap(40, 40, 40)
                .addComponent(btnRegistrarRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblTituloRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolAlta.setText("Alta de Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRolAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRolAltaActionPerformed

    }//GEN-LAST:event_btnRegistrarRolAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarRolAlta;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblDescripcionRolAlta;
    private javax.swing.JLabel lblDescripcionRolAlta1;
    private javax.swing.JLabel lblNombreRolAlta;
    private javax.swing.JLabel lblNombreRolAlta1;
    private javax.swing.JLabel lblNombreRolAlta2;
    private javax.swing.JLabel lblTituloRolAlta;
    private javax.swing.JPanel panDatosRolAlta;
    private javax.swing.JTextField txtNombreRolAlta;
    private javax.swing.JTextField txtNombreRolAlta1;
    private javax.swing.JTextField txtNombreRolAlta2;
    // End of variables declaration//GEN-END:variables
}
