package vista;

import controlador.GestionRol;
import javax.swing.JOptionPane;
import modelo.Rol;

public class AltaRol extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    GestionRol gestionRol = new GestionRol();
    
    public AltaRol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolAlta = new javax.swing.JPanel();
        lblNombreRolAlta = new javax.swing.JLabel();
        lblDescripcionRolAlta = new javax.swing.JLabel();
        txtNombreRolAlta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcionRolAlta = new javax.swing.JTextArea();
        btnRegistrarRolAlta = new javax.swing.JButton();
        lblTituloRolAlta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolAlta.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolAlta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolAlta.setOpaque(false);

        lblNombreRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta.setText("Nombre");

        lblDescripcionRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolAlta.setText("Descripción");

        txtaDescripcionRolAlta.setColumns(20);
        txtaDescripcionRolAlta.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcionRolAlta);

        btnRegistrarRolAlta.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarRolAlta.setText("Registrar Rol");
        btnRegistrarRolAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRolAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDatosRolAltaLayout = new javax.swing.GroupLayout(panDatosRolAlta);
        panDatosRolAlta.setLayout(panDatosRolAltaLayout);
        panDatosRolAltaLayout.setHorizontalGroup(
            panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreRolAlta)
                    .addComponent(lblDescripcionRolAlta))
                .addGap(41, 41, 41)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosRolAltaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        panDatosRolAltaLayout.setVerticalGroup(
            panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRolAlta))
                .addGap(59, 59, 59)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionRolAlta)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnRegistrarRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lblTituloRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolAlta.setText("Alta de Rol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRolAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRolAltaActionPerformed
        GestionRol gestionRol = new GestionRol();
        Rol rol = new Rol();
        rol.setNombre(txtNombreRolAlta.getText());
        rol.setDescripcion(txtaDescripcionRolAlta.getText());
        //Byte.toUnsignedInt(b); regresar a entero
        if(gestionRol.alta(rol) == true){
            JOptionPane.showMessageDialog(null, "El Rol " + rol.getNombre()
                    + "fue registrado");
            txtNombreRolAlta.setText("");
            txtaDescripcionRolAlta.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Rol no registrado");
        }
    }//GEN-LAST:event_btnRegistrarRolAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarRolAlta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionRolAlta;
    private javax.swing.JLabel lblNombreRolAlta;
    private javax.swing.JLabel lblTituloRolAlta;
    private javax.swing.JPanel panDatosRolAlta;
    private javax.swing.JTextField txtNombreRolAlta;
    private javax.swing.JTextArea txtaDescripcionRolAlta;
    // End of variables declaration//GEN-END:variables
}
