/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class EliminarCompra extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public EliminarCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolEliminar = new javax.swing.JPanel();
        lblNombreRolModificar = new javax.swing.JLabel();
        lblDescripcionRolModificar = new javax.swing.JLabel();
        btnAceptarRolEliminar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTituloRolEliminar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolEliminar.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolEliminar.setOpaque(false);

        lblNombreRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolModificar.setText("Numero de compra");

        lblDescripcionRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolModificar.setText("Detalle");

        btnAceptarRolEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnAceptarRolEliminar.setText("Aceptar");

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout panDatosRolEliminarLayout = new javax.swing.GroupLayout(panDatosRolEliminar);
        panDatosRolEliminar.setLayout(panDatosRolEliminarLayout);
        panDatosRolEliminarLayout.setHorizontalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                                .addComponent(lblNombreRolModificar)
                                .addGap(36, 36, 36)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescripcionRolModificar)
                            .addComponent(jScrollPane2)))
                    .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panDatosRolEliminarLayout.setVerticalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRolModificar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(lblDescripcionRolModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        lblTituloRolEliminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolEliminar.setText("Eliminar Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRolEliminar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDescripcionRolModificar;
    private javax.swing.JLabel lblNombreRolModificar;
    private javax.swing.JLabel lblTituloRolEliminar;
    private javax.swing.JPanel panDatosRolEliminar;
    // End of variables declaration//GEN-END:variables
}
