/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class EliminarMaterial extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public EliminarMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolEliminar = new javax.swing.JPanel();
        lblNombreRolModificar = new javax.swing.JLabel();
        btnAceptarRolEliminar = new javax.swing.JButton();
        cbxNombreRolEliminar = new javax.swing.JComboBox<>();
        lblTituloRolEliminar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolEliminar.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Matrial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolEliminar.setOpaque(false);

        lblNombreRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolModificar.setText("Tipo");

        btnAceptarRolEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnAceptarRolEliminar.setText("Aceptar");

        cbxNombreRolEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panDatosRolEliminarLayout = new javax.swing.GroupLayout(panDatosRolEliminar);
        panDatosRolEliminar.setLayout(panDatosRolEliminarLayout);
        panDatosRolEliminarLayout.setHorizontalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lblNombreRolModificar)
                .addGap(63, 63, 63)
                .addComponent(cbxNombreRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDatosRolEliminarLayout.setVerticalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRolModificar)
                    .addComponent(cbxNombreRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        lblTituloRolEliminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolEliminar.setText("Eliminar Material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRolEliminar;
    private javax.swing.JComboBox<String> cbxNombreRolEliminar;
    private javax.swing.JLabel lblNombreRolModificar;
    private javax.swing.JLabel lblTituloRolEliminar;
    private javax.swing.JPanel panDatosRolEliminar;
    // End of variables declaration//GEN-END:variables
}
