/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author hp
 */
public class EliminarRol extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public EliminarRol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolEliminar = new javax.swing.JPanel();
        lblNombreRolModificar = new javax.swing.JLabel();
        lblDescripcionRolModificar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcionRolEliminar = new javax.swing.JTextArea();
        btnAceptarRolEliminar = new javax.swing.JButton();
        cbxNombreRolEliminar = new javax.swing.JComboBox<>();
        lblTituloRolEliminar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolEliminar.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolEliminar.setOpaque(false);

        lblNombreRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolModificar.setText("Nombre");

        lblDescripcionRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolModificar.setText("Descripción");

        txtaDescripcionRolEliminar.setColumns(20);
        txtaDescripcionRolEliminar.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcionRolEliminar);

        btnAceptarRolEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnAceptarRolEliminar.setText("Aceptar");

        cbxNombreRolEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panDatosRolEliminarLayout = new javax.swing.GroupLayout(panDatosRolEliminar);
        panDatosRolEliminar.setLayout(panDatosRolEliminarLayout);
        panDatosRolEliminarLayout.setHorizontalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreRolModificar)
                            .addComponent(lblDescripcionRolModificar))
                        .addGap(41, 41, 41)
                        .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(cbxNombreRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panDatosRolEliminarLayout.setVerticalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRolModificar)
                    .addComponent(cbxNombreRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionRolModificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblTituloRolEliminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolEliminar.setText("Eliminar Rol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRolEliminar;
    private javax.swing.JComboBox<String> cbxNombreRolEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionRolModificar;
    private javax.swing.JLabel lblNombreRolModificar;
    private javax.swing.JLabel lblTituloRolEliminar;
    private javax.swing.JPanel panDatosRolEliminar;
    private javax.swing.JTextArea txtaDescripcionRolEliminar;
    // End of variables declaration//GEN-END:variables
}
