/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.GestionRol;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Rol;

/**
 *
 * @author hp
 */
public class EliminarRol extends javax.swing.JPanel {
    private FondoPanel fondo = new FondoPanel();
    private GestionRol gestionRol = new GestionRol();
    private List<Rol> lista;
    private Rol rol;
    
    public EliminarRol() {
        initComponents();
        this.rol = new Rol();
        idRoles();
    }
    
    private void idRoles() {
        this.lista = gestionRol.lista();
        this.lista.stream().forEach(rol 
                -> cbxNombreRolEliminar.addItem(rol.getNombre()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolEliminar = new javax.swing.JPanel();
        lblNombreRolModificar = new javax.swing.JLabel();
        lblDescripcionRolModificar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcionRolEliminar = new javax.swing.JTextArea();
        btnAceptarRolEliminar = new javax.swing.JButton();
        cbxNombreRolEliminar = new javax.swing.JComboBox<>();
        lblTituloRolEliminar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolEliminar.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolEliminar.setOpaque(false);

        lblNombreRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolModificar.setText("Nombre");

        lblDescripcionRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolModificar.setText("Descripción");

        txtaDescripcionRolEliminar.setColumns(20);
        txtaDescripcionRolEliminar.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcionRolEliminar);

        btnAceptarRolEliminar.setBackground(new java.awt.Color(255, 204, 204));
        btnAceptarRolEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAceptarRolEliminar.setText("Eliminar");
        btnAceptarRolEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRolEliminarActionPerformed(evt);
            }
        });

        cbxNombreRolEliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNombreRolEliminarItemStateChanged(evt);
            }
        });
        cbxNombreRolEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxNombreRolEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbxNombreRolEliminarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxNombreRolEliminarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panDatosRolEliminarLayout = new javax.swing.GroupLayout(panDatosRolEliminar);
        panDatosRolEliminar.setLayout(panDatosRolEliminarLayout);
        panDatosRolEliminarLayout.setHorizontalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreRolModificar)
                            .addComponent(lblDescripcionRolModificar))
                        .addGap(41, 41, 41)
                        .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                            .addComponent(cbxNombreRolEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panDatosRolEliminarLayout.setVerticalGroup(
            panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolEliminarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRolModificar)
                    .addComponent(cbxNombreRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(panDatosRolEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionRolModificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAceptarRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblTituloRolEliminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolEliminar.setText("Eliminar Rol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarRolEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRolEliminarActionPerformed
        int i = cbxNombreRolEliminar.getSelectedIndex();
        if (gestionRol.eliminar(lista.get(i)) == true){
           //Método que actualice la vista 
           cbxNombreRolEliminar.remove(i);
        }else{
            JOptionPane.showMessageDialog(null, "No fue posible eliminar el Rol");
        }
    }//GEN-LAST:event_btnAceptarRolEliminarActionPerformed

    private void cbxNombreRolEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxNombreRolEliminarMouseClicked

    }//GEN-LAST:event_cbxNombreRolEliminarMouseClicked

    private void cbxNombreRolEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxNombreRolEliminarMouseEntered

    }//GEN-LAST:event_cbxNombreRolEliminarMouseEntered

    private void cbxNombreRolEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxNombreRolEliminarMousePressed

    }//GEN-LAST:event_cbxNombreRolEliminarMousePressed

    private void cbxNombreRolEliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNombreRolEliminarItemStateChanged
        int i = cbxNombreRolEliminar.getSelectedIndex();
        txtaDescripcionRolEliminar.setText(lista.get(i).getDescripcion());
    }//GEN-LAST:event_cbxNombreRolEliminarItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarRolEliminar;
    private javax.swing.JComboBox<String> cbxNombreRolEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionRolModificar;
    private javax.swing.JLabel lblNombreRolModificar;
    private javax.swing.JLabel lblTituloRolEliminar;
    private javax.swing.JPanel panDatosRolEliminar;
    private javax.swing.JTextArea txtaDescripcionRolEliminar;
    // End of variables declaration//GEN-END:variables
}
