/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;

public class MenuPrincipalSistema extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    Usuario usuario;
    
    public MenuPrincipalSistema() {
        initComponents();
        this.setContentPane(fondo);
        this.setTitle("Menú Sistema Reciclados Mexicanos");
        this.setLocationRelativeTo(null);
    }
    
    public MenuPrincipalSistema(Usuario usuario) {
        initComponents();
        this.setContentPane(fondo);
        this.setTitle("Menú Sistema Reciclados Mexicanos");
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        setPrivilegios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuSesion = new javax.swing.JMenu();
        itemCerrarSesión = new javax.swing.JMenuItem();
        itemSalirSistema = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        itemComprar = new javax.swing.JMenuItem();
        itemCorregirCompra = new javax.swing.JMenuItem();
        itemEliminarCompra = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        itemVender = new javax.swing.JMenuItem();
        itemCorregirVenta = new javax.swing.JMenuItem();
        itemCancelarVenta = new javax.swing.JMenuItem();
        menuMateriales = new javax.swing.JMenu();
        itemAltaMaterial = new javax.swing.JMenuItem();
        itemEditarMaterial = new javax.swing.JMenuItem();
        itemEliminarMaterial = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        itemAltaProveedor = new javax.swing.JMenuItem();
        itemEditarProveedor = new javax.swing.JMenuItem();
        itemEliminarProveedor = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        itemAltaCliente = new javax.swing.JMenuItem();
        itemEditarCliente = new javax.swing.JMenuItem();
        itemEliminarCliente = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReporteVentas = new javax.swing.JMenuItem();
        itemReporteCompras = new javax.swing.JMenuItem();
        itemReporteMateriales = new javax.swing.JMenuItem();
        itemReporteProveedores = new javax.swing.JMenuItem();
        itemReporteClientes = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemAltaUsuario = new javax.swing.JMenuItem();
        itemEditarUsuario = new javax.swing.JMenuItem();
        itemEliminarUsuario = new javax.swing.JMenuItem();
        menuRoles = new javax.swing.JMenu();
        itemAltaRol = new javax.swing.JMenuItem();
        itemEditarRol = new javax.swing.JMenuItem();
        itemEliminarRol = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuSesion.setText("Sesión");
        menuSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemCerrarSesión.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemCerrarSesión.setText("Cerrar sesión");
        itemCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesiónActionPerformed(evt);
            }
        });
        menuSesion.add(itemCerrarSesión);

        itemSalirSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemSalirSistema.setText("Salir");
        itemSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirSistemaActionPerformed(evt);
            }
        });
        menuSesion.add(itemSalirSistema);

        jMenuBar1.add(menuSesion);

        menuCompras.setText("Compras");
        menuCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemComprar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemComprar.setText("Comprar");
        menuCompras.add(itemComprar);

        itemCorregirCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemCorregirCompra.setText("Modificar Compra");
        menuCompras.add(itemCorregirCompra);

        itemEliminarCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEliminarCompra.setText("Eliminar Compra");
        menuCompras.add(itemEliminarCompra);

        jMenuBar1.add(menuCompras);

        menuVentas.setText("Ventas");
        menuVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemVender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemVender.setText("Vender");
        menuVentas.add(itemVender);

        itemCorregirVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemCorregirVenta.setText("Modificar Venta");
        menuVentas.add(itemCorregirVenta);

        itemCancelarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemCancelarVenta.setText("Cancelar Venta");
        menuVentas.add(itemCancelarVenta);

        jMenuBar1.add(menuVentas);

        menuMateriales.setText("Materiales");
        menuMateriales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemAltaMaterial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemAltaMaterial.setText("Alta Material");
        menuMateriales.add(itemAltaMaterial);

        itemEditarMaterial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEditarMaterial.setText("Editar Material");
        menuMateriales.add(itemEditarMaterial);

        itemEliminarMaterial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEliminarMaterial.setText("Eliminar Material");
        menuMateriales.add(itemEliminarMaterial);

        jMenuBar1.add(menuMateriales);

        menuProveedores.setText("Proveedores");
        menuProveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemAltaProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemAltaProveedor.setText("Alta proveedor");
        menuProveedores.add(itemAltaProveedor);

        itemEditarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEditarProveedor.setText("Editar proveedor");
        menuProveedores.add(itemEditarProveedor);

        itemEliminarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEliminarProveedor.setText("Eliminar proveedor");
        menuProveedores.add(itemEliminarProveedor);

        jMenuBar1.add(menuProveedores);

        menuClientes.setText("Clientes");
        menuClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemAltaCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemAltaCliente.setText("Alta Cliente");
        menuClientes.add(itemAltaCliente);

        itemEditarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEditarCliente.setText("Editar Cliente");
        menuClientes.add(itemEditarCliente);

        itemEliminarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEliminarCliente.setText("Eliminar Cliente");
        menuClientes.add(itemEliminarCliente);

        jMenuBar1.add(menuClientes);

        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemReporteVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemReporteVentas.setText("Reporte de Ventas");
        menuReportes.add(itemReporteVentas);

        itemReporteCompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemReporteCompras.setText("Reporte de Compras");
        menuReportes.add(itemReporteCompras);

        itemReporteMateriales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemReporteMateriales.setText("Reporte de Materiales");
        menuReportes.add(itemReporteMateriales);

        itemReporteProveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemReporteProveedores.setText("Reporte de Proveedores");
        menuReportes.add(itemReporteProveedores);

        itemReporteClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemReporteClientes.setText("Reporte de Clientes");
        menuReportes.add(itemReporteClientes);

        jMenuBar1.add(menuReportes);

        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemAltaUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemAltaUsuario.setText("Alta Usuario");
        menuUsuarios.add(itemAltaUsuario);

        itemEditarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEditarUsuario.setText("Editar Usuario");
        menuUsuarios.add(itemEditarUsuario);

        itemEliminarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEliminarUsuario.setText("Eliminar Usuario");
        menuUsuarios.add(itemEliminarUsuario);

        jMenuBar1.add(menuUsuarios);

        menuRoles.setText("Roles");
        menuRoles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        itemAltaRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemAltaRol.setText("Alta Rol");
        menuRoles.add(itemAltaRol);

        itemEditarRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEditarRol.setText("Editar Rol");
        menuRoles.add(itemEditarRol);

        itemEliminarRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemEliminarRol.setText("Eliminar Rol");
        menuRoles.add(itemEliminarRol);

        jMenuBar1.add(menuRoles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirSistemaActionPerformed
        int confirmarSalida = JOptionPane.showConfirmDialog(null, 
            "¿Quieres salir del sistema?","Mensaje de sistema!!",
            JOptionPane.YES_NO_OPTION);
        //estructura de control selectiva id simple
        if (confirmarSalida == 0) {
            System.exit(0);//cierra ventana
        }
    }//GEN-LAST:event_itemSalirSistemaActionPerformed

    private void itemCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesiónActionPerformed
        ValidarUsuario ventanaValidarUsuario = new ValidarUsuario();
        ventanaValidarUsuario.setVisible(true);
        this.hide();
    }//GEN-LAST:event_itemCerrarSesiónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalSistema().setVisible(true);
            }
        });
    }
    
    private void setPrivilegios () {
        if (this.usuario.getIdRol() == 1) {
            
        }else if (this.usuario.getIdRol() == 2) {
            menuUsuarios.setVisible(false);
            menuRoles.setVisible(false);
        }else if (this.usuario.getIdRol() == 3) {
            menuUsuarios.setVisible(false);
            menuRoles.setVisible(false);
            menuReportes.setVisible(false);
            menuClientes.setVisible(false);
            menuProveedores.setVisible(false);
            menuMateriales.setVisible(false);
            menuVentas.setVisible(false);
            itemCorregirCompra.setVisible(false);
            itemEliminarCompra.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAltaCliente;
    private javax.swing.JMenuItem itemAltaMaterial;
    private javax.swing.JMenuItem itemAltaProveedor;
    private javax.swing.JMenuItem itemAltaRol;
    private javax.swing.JMenuItem itemAltaUsuario;
    private javax.swing.JMenuItem itemCancelarVenta;
    private javax.swing.JMenuItem itemCerrarSesión;
    private javax.swing.JMenuItem itemComprar;
    private javax.swing.JMenuItem itemCorregirCompra;
    private javax.swing.JMenuItem itemCorregirVenta;
    private javax.swing.JMenuItem itemEditarCliente;
    private javax.swing.JMenuItem itemEditarMaterial;
    private javax.swing.JMenuItem itemEditarProveedor;
    private javax.swing.JMenuItem itemEditarRol;
    private javax.swing.JMenuItem itemEditarUsuario;
    private javax.swing.JMenuItem itemEliminarCliente;
    private javax.swing.JMenuItem itemEliminarCompra;
    private javax.swing.JMenuItem itemEliminarMaterial;
    private javax.swing.JMenuItem itemEliminarProveedor;
    private javax.swing.JMenuItem itemEliminarRol;
    private javax.swing.JMenuItem itemEliminarUsuario;
    private javax.swing.JMenuItem itemReporteClientes;
    private javax.swing.JMenuItem itemReporteCompras;
    private javax.swing.JMenuItem itemReporteMateriales;
    private javax.swing.JMenuItem itemReporteProveedores;
    private javax.swing.JMenuItem itemReporteVentas;
    private javax.swing.JMenuItem itemSalirSistema;
    private javax.swing.JMenuItem itemVender;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuMateriales;
    private javax.swing.JMenu menuProveedores;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuRoles;
    private javax.swing.JMenu menuSesion;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
