package vista;

import controlador.GestionRol;
import java.awt.Color;
import modelo.Rol;

public class ModificarProveedor extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public ModificarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosProveedorAlta = new javax.swing.JPanel();
        lblNombreProveedorAlta = new javax.swing.JLabel();
        lblTelefonoProveedorAlta = new javax.swing.JLabel();
        btnRegistrarProveedorAlta = new javax.swing.JButton();
        lblRFCProveedorAlta = new javax.swing.JLabel();
        txtRFCProveedorAlta = new javax.swing.JTextField();
        txtTelefonoProveedorAlta = new javax.swing.JTextField();
        lblDireccionProveedorAlta = new javax.swing.JLabel();
        txtDireccionProveedorAlta = new javax.swing.JTextField();
        lblEmailProveedorAlta = new javax.swing.JLabel();
        txtEmailProveedorAlta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTituloProveedorAlta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosProveedorAlta.setBackground(new java.awt.Color(182, 215, 168));
        panDatosProveedorAlta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosProveedorAlta.setOpaque(false);

        lblNombreProveedorAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreProveedorAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProveedorAlta.setText("Razón Social");

        lblTelefonoProveedorAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefonoProveedorAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefonoProveedorAlta.setText("Teléfono");

        btnRegistrarProveedorAlta.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarProveedorAlta.setText("Actualizar");
        btnRegistrarProveedorAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorAltaActionPerformed(evt);
            }
        });

        lblRFCProveedorAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRFCProveedorAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblRFCProveedorAlta.setText("RFC");

        lblDireccionProveedorAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDireccionProveedorAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionProveedorAlta.setText("Dirección");

        lblEmailProveedorAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailProveedorAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailProveedorAlta.setText("e-mail");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panDatosProveedorAltaLayout = new javax.swing.GroupLayout(panDatosProveedorAlta);
        panDatosProveedorAlta.setLayout(panDatosProveedorAltaLayout);
        panDatosProveedorAltaLayout.setHorizontalGroup(
            panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosProveedorAltaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRegistrarProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211))
                            .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                                    .addComponent(lblEmailProveedorAlta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmailProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                                    .addComponent(lblDireccionProveedorAlta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDireccionProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                                    .addComponent(lblRFCProveedorAlta)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtRFCProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblTelefonoProveedorAlta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblNombreProveedorAlta)))
                    .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panDatosProveedorAltaLayout.setVerticalGroup(
            panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosProveedorAltaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProveedorAlta)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoProveedorAlta)
                    .addComponent(txtRFCProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRFCProveedorAlta))
                .addGap(61, 61, 61)
                .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionProveedorAlta))
                .addGap(52, 52, 52)
                .addGroup(panDatosProveedorAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailProveedorAlta))
                .addGap(40, 40, 40)
                .addComponent(btnRegistrarProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblTituloProveedorAlta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloProveedorAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloProveedorAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloProveedorAlta.setText("Modificar Proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloProveedorAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloProveedorAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosProveedorAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProveedorAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorAltaActionPerformed

    }//GEN-LAST:event_btnRegistrarProveedorAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarProveedorAlta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblDireccionProveedorAlta;
    private javax.swing.JLabel lblEmailProveedorAlta;
    private javax.swing.JLabel lblNombreProveedorAlta;
    private javax.swing.JLabel lblRFCProveedorAlta;
    private javax.swing.JLabel lblTelefonoProveedorAlta;
    private javax.swing.JLabel lblTituloProveedorAlta;
    private javax.swing.JPanel panDatosProveedorAlta;
    private javax.swing.JTextField txtDireccionProveedorAlta;
    private javax.swing.JTextField txtEmailProveedorAlta;
    private javax.swing.JTextField txtRFCProveedorAlta;
    private javax.swing.JTextField txtTelefonoProveedorAlta;
    // End of variables declaration//GEN-END:variables
}
