/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.GestionRol;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Rol;

/**
 *
 * @author hp
 */
public class ModificarRol extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    private GestionRol gestionRol = new GestionRol();
    private List<Rol> lista;
    private Rol rol;
    
    public ModificarRol() {
        initComponents();
        this.rol = new Rol();
        idRoles();
    }
    
     private void idRoles() {
        this.lista = gestionRol.lista();
        this.lista.stream().forEach(rol 
                -> cbxNombreRolModificar.addItem(rol.getNombre()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolModificar = new javax.swing.JPanel();
        lblNombreRolModificar = new javax.swing.JLabel();
        lblDescripcionRolModificar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripcionRolModificar = new javax.swing.JTextArea();
        btnActualizarRolModificar = new javax.swing.JButton();
        cbxNombreRolModificar = new javax.swing.JComboBox<>();
        lblTituloRolModificar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolModificar.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolModificar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolModificar.setOpaque(false);

        lblNombreRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolModificar.setText("Nombre");

        lblDescripcionRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolModificar.setText("Descripción");

        txtaDescripcionRolModificar.setColumns(20);
        txtaDescripcionRolModificar.setRows(5);
        jScrollPane1.setViewportView(txtaDescripcionRolModificar);

        btnActualizarRolModificar.setBackground(new java.awt.Color(102, 102, 102));
        btnActualizarRolModificar.setText("Actualizar Rol");
        btnActualizarRolModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarRolModificarActionPerformed(evt);
            }
        });

        cbxNombreRolModificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNombreRolModificarItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panDatosRolModificarLayout = new javax.swing.GroupLayout(panDatosRolModificar);
        panDatosRolModificar.setLayout(panDatosRolModificarLayout);
        panDatosRolModificarLayout.setHorizontalGroup(
            panDatosRolModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolModificarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(panDatosRolModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreRolModificar)
                    .addComponent(lblDescripcionRolModificar))
                .addGap(41, 41, 41)
                .addGroup(panDatosRolModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(cbxNombreRolModificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosRolModificarLayout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(btnActualizarRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        panDatosRolModificarLayout.setVerticalGroup(
            panDatosRolModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolModificarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panDatosRolModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRolModificar)
                    .addComponent(cbxNombreRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(panDatosRolModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionRolModificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnActualizarRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        lblTituloRolModificar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolModificar.setText("Modificar Rol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNombreRolModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNombreRolModificarItemStateChanged
        int i = cbxNombreRolModificar.getSelectedIndex();
        txtaDescripcionRolModificar.setText(lista.get(i).getDescripcion());
    }//GEN-LAST:event_cbxNombreRolModificarItemStateChanged

    private void btnActualizarRolModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarRolModificarActionPerformed
        GestionRol gestionRol = new GestionRol();
        Rol rol = new Rol();
        int i = cbxNombreRolModificar.getSelectedIndex();
        
        rol.setNombre(lista.get(i).getNombre());
        rol.setDescripcion(txtaDescripcionRolModificar.getText());
        //Byte.toUnsignedInt(b); regresar a entero
        if(gestionRol.alta(rol) == true){
            JOptionPane.showMessageDialog(null, "El Rol " + rol.getNombre()
                    + "se actualizo correctamente");
        }else{
            JOptionPane.showMessageDialog(null, "Rol no actualizado");
        }
    }//GEN-LAST:event_btnActualizarRolModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarRolModificar;
    private javax.swing.JComboBox<String> cbxNombreRolModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionRolModificar;
    private javax.swing.JLabel lblNombreRolModificar;
    private javax.swing.JLabel lblTituloRolModificar;
    private javax.swing.JPanel panDatosRolModificar;
    private javax.swing.JTextArea txtaDescripcionRolModificar;
    // End of variables declaration//GEN-END:variables
}
