package vista;

import controlador.GestionRol;
import java.awt.Color;
import modelo.Rol;

public class ModificarMaterial extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public ModificarMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosMaterialAlta = new javax.swing.JPanel();
        lblTipoMaterialAlta = new javax.swing.JLabel();
        lblExistenciaMaterialAlta = new javax.swing.JLabel();
        btnRegistrarAltaMaterial = new javax.swing.JButton();
        lblClaveMaterialAlta = new javax.swing.JLabel();
        txtClaveMaterialAlta = new javax.swing.JTextField();
        txtPrecioVentaMaterialAlta = new javax.swing.JTextField();
        lblPrecioVentaMaterialAlta = new javax.swing.JLabel();
        txtExistenciaMaterialAlta = new javax.swing.JTextField();
        lblPrecioCompraMaterialAlta = new javax.swing.JLabel();
        txtPrecioCompraMaterialAlta = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTituloMaterialAlta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosMaterialAlta.setBackground(new java.awt.Color(182, 215, 168));
        panDatosMaterialAlta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Material", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosMaterialAlta.setOpaque(false);

        lblTipoMaterialAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoMaterialAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoMaterialAlta.setText("Tipo");

        lblExistenciaMaterialAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExistenciaMaterialAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblExistenciaMaterialAlta.setText("Existencia");

        btnRegistrarAltaMaterial.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarAltaMaterial.setText("Actualizar");
        btnRegistrarAltaMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAltaMaterialActionPerformed(evt);
            }
        });

        lblClaveMaterialAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClaveMaterialAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblClaveMaterialAlta.setText("Clave");

        lblPrecioVentaMaterialAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioVentaMaterialAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioVentaMaterialAlta.setText("Precio venta");

        lblPrecioCompraMaterialAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioCompraMaterialAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioCompraMaterialAlta.setText("Precio compra");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panDatosMaterialAltaLayout = new javax.swing.GroupLayout(panDatosMaterialAlta);
        panDatosMaterialAlta.setLayout(panDatosMaterialAltaLayout);
        panDatosMaterialAltaLayout.setHorizontalGroup(
            panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosMaterialAltaLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoMaterialAlta)
                    .addComponent(lblClaveMaterialAlta)
                    .addComponent(lblExistenciaMaterialAlta))
                .addGap(34, 34, 34)
                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosMaterialAltaLayout.createSequentialGroup()
                        .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrarAltaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panDatosMaterialAltaLayout.createSequentialGroup()
                                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtExistenciaMaterialAlta)
                                    .addComponent(txtClaveMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioCompraMaterialAlta)
                                    .addComponent(lblPrecioVentaMaterialAlta))))
                        .addGap(18, 18, 18)
                        .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioCompraMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioVentaMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        panDatosMaterialAltaLayout.setVerticalGroup(
            panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosMaterialAltaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMaterialAlta)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVentaMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClaveMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClaveMaterialAlta)
                    .addComponent(lblPrecioVentaMaterialAlta))
                .addGap(61, 61, 61)
                .addGroup(panDatosMaterialAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExistenciaMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioCompraMaterialAlta)
                    .addComponent(txtPrecioCompraMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExistenciaMaterialAlta))
                .addGap(60, 60, 60)
                .addComponent(btnRegistrarAltaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblTituloMaterialAlta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloMaterialAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloMaterialAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMaterialAlta.setText("Material Material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloMaterialAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMaterialAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosMaterialAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAltaMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAltaMaterialActionPerformed

    }//GEN-LAST:event_btnRegistrarAltaMaterialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAltaMaterial;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblClaveMaterialAlta;
    private javax.swing.JLabel lblExistenciaMaterialAlta;
    private javax.swing.JLabel lblPrecioCompraMaterialAlta;
    private javax.swing.JLabel lblPrecioVentaMaterialAlta;
    private javax.swing.JLabel lblTipoMaterialAlta;
    private javax.swing.JLabel lblTituloMaterialAlta;
    private javax.swing.JPanel panDatosMaterialAlta;
    private javax.swing.JTextField txtClaveMaterialAlta;
    private javax.swing.JTextField txtExistenciaMaterialAlta;
    private javax.swing.JTextField txtPrecioCompraMaterialAlta;
    private javax.swing.JTextField txtPrecioVentaMaterialAlta;
    // End of variables declaration//GEN-END:variables
}
