package vista;

import controlador.GestionRol;
import java.awt.Color;
import modelo.Rol;

public class ModificarCliente extends javax.swing.JPanel {
    FondoPanel fondo = new FondoPanel();
    
    public ModificarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosRolAlta = new javax.swing.JPanel();
        lblNombreRolAlta = new javax.swing.JLabel();
        lblDescripcionRolAlta = new javax.swing.JLabel();
        btnRegistrarRolAlta = new javax.swing.JButton();
        lblDescripcionRolAlta1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblNombreRolAlta1 = new javax.swing.JLabel();
        txtNombreRolAlta1 = new javax.swing.JTextField();
        lblNombreRolAlta2 = new javax.swing.JLabel();
        txtNombreRolAlta2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblDescripcionRolAlta2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        lblTituloRolAlta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 83, 148));

        panDatosRolAlta.setBackground(new java.awt.Color(182, 215, 168));
        panDatosRolAlta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panDatosRolAlta.setOpaque(false);

        lblNombreRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta.setText("Razón Social");

        lblDescripcionRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolAlta.setText("Número de cliente");

        btnRegistrarRolAlta.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrarRolAlta.setText("Actualizar");
        btnRegistrarRolAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRolAltaActionPerformed(evt);
            }
        });

        lblDescripcionRolAlta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolAlta1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolAlta1.setText("RFC");

        lblNombreRolAlta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta1.setText("Dirección");

        lblNombreRolAlta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreRolAlta2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreRolAlta2.setText("e-mail");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDescripcionRolAlta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcionRolAlta2.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionRolAlta2.setText("Teléfono");

        javax.swing.GroupLayout panDatosRolAltaLayout = new javax.swing.GroupLayout(panDatosRolAlta);
        panDatosRolAlta.setLayout(panDatosRolAltaLayout);
        panDatosRolAltaLayout.setHorizontalGroup(
            panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosRolAltaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegistrarRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                            .addComponent(lblNombreRolAlta)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblDescripcionRolAlta)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField3))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panDatosRolAltaLayout.createSequentialGroup()
                            .addComponent(lblDescripcionRolAlta1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblDescripcionRolAlta2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panDatosRolAltaLayout.createSequentialGroup()
                            .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreRolAlta1)
                                .addComponent(lblNombreRolAlta2))
                            .addGap(18, 18, 18)
                            .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreRolAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreRolAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panDatosRolAltaLayout.setVerticalGroup(
            panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosRolAltaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRolAlta)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionRolAlta)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcionRolAlta1)
                    .addComponent(lblDescripcionRolAlta2))
                .addGap(50, 50, 50)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRolAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRolAlta1))
                .addGap(46, 46, 46)
                .addGroup(panDatosRolAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRolAlta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreRolAlta2))
                .addGap(40, 40, 40)
                .addComponent(btnRegistrarRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lblTituloRolAlta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloRolAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRolAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRolAlta.setText("Modificar Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRolAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panDatosRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloRolAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosRolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarRolAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRolAltaActionPerformed

    }//GEN-LAST:event_btnRegistrarRolAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarRolAlta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblDescripcionRolAlta;
    private javax.swing.JLabel lblDescripcionRolAlta1;
    private javax.swing.JLabel lblDescripcionRolAlta2;
    private javax.swing.JLabel lblNombreRolAlta;
    private javax.swing.JLabel lblNombreRolAlta1;
    private javax.swing.JLabel lblNombreRolAlta2;
    private javax.swing.JLabel lblTituloRolAlta;
    private javax.swing.JPanel panDatosRolAlta;
    private javax.swing.JTextField txtNombreRolAlta1;
    private javax.swing.JTextField txtNombreRolAlta2;
    // End of variables declaration//GEN-END:variables
}
