package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;

public class ValidarUsuario extends javax.swing.JFrame {
    FondoPanel fondo;
    Usuario usuario;
    
    public ValidarUsuario() {
        fondo = new FondoPanel();
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        fondo.escalarImagen(this.lblLogoLogin, "src/img/logo.png");
        this.setTitle("Ingreso al Sistema Reciclados Mexicanos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panLogeo = new javax.swing.JPanel();
        txtUsuarioLogin = new javax.swing.JTextField();
        lblUsuarioLogin = new javax.swing.JLabel();
        lblClaveIngresoLogin = new javax.swing.JLabel();
        txtClaveIngresoLogin = new javax.swing.JPasswordField();
        lblLogoLogin = new javax.swing.JLabel();
        lblNombre1Empresa = new javax.swing.JLabel();
        lblNombre2empresa = new javax.swing.JLabel();
        btnIngresarLogin = new javax.swing.JButton();
        panPieLogin = new javax.swing.JPanel();
        lblCopyright = new javax.swing.JLabel();

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panLogeo.setBackground(new java.awt.Color(160, 189, 207));
        panLogeo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bienvenido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panLogeo.setToolTipText("");
        panLogeo.setOpaque(false);

        txtUsuarioLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioLoginActionPerformed(evt);
            }
        });

        lblUsuarioLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuarioLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioLogin.setText("Usuario");

        lblClaveIngresoLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClaveIngresoLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblClaveIngresoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClaveIngresoLogin.setText("Contraseña");

        txtClaveIngresoLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtClaveIngresoLogin.setText("1234");

        lblNombre1Empresa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombre1Empresa.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1Empresa.setText("Reciclados ");

        lblNombre2empresa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombre2empresa.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2empresa.setText("Mexicanos S.A. de C.V.");

        btnIngresarLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresarLogin.setText("Ingresar");
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLogeoLayout = new javax.swing.GroupLayout(panLogeo);
        panLogeo.setLayout(panLogeoLayout);
        panLogeoLayout.setHorizontalGroup(
            panLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogeoLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(panLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLogeoLayout.createSequentialGroup()
                        .addGroup(panLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre2empresa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLogeoLayout.createSequentialGroup()
                                .addGroup(panLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre1Empresa))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLogeoLayout.createSequentialGroup()
                                .addGroup(panLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClaveIngresoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClaveIngresoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panLogeoLayout.createSequentialGroup()
                        .addComponent(btnIngresarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        panLogeoLayout.setVerticalGroup(
            panLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogeoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre1Empresa)
                .addGap(10, 10, 10)
                .addComponent(lblNombre2empresa)
                .addGap(31, 31, 31)
                .addComponent(lblUsuarioLogin)
                .addGap(18, 18, 18)
                .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClaveIngresoLogin)
                .addGap(18, 18, 18)
                .addComponent(txtClaveIngresoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnIngresarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panPieLogin.setOpaque(false);

        lblCopyright.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblCopyright.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("@2022  Login form. All Rightd Reserved | Design by Rivera");

        javax.swing.GroupLayout panPieLoginLayout = new javax.swing.GroupLayout(panPieLogin);
        panPieLogin.setLayout(panPieLoginLayout);
        panPieLoginLayout.setHorizontalGroup(
            panPieLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCopyright, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panPieLoginLayout.setVerticalGroup(
            panPieLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPieLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCopyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPieLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(panLogeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(panLogeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panPieLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioLoginActionPerformed

    private void btnIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoginActionPerformed
        this.usuario = new Usuario();
        this.usuario.setIdRol(1);
        this.usuario.setNombreUsuario("User");
        MenuPrincipalSistema menuSistema = new MenuPrincipalSistema(this.usuario);
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema\n"
                                + usuario.getNombreUsuario());
        menuSistema.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnIngresarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblClaveIngresoLogin;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblLogoLogin;
    private javax.swing.JLabel lblNombre1Empresa;
    private javax.swing.JLabel lblNombre2empresa;
    private javax.swing.JLabel lblUsuarioLogin;
    private javax.swing.JPanel panLogeo;
    private javax.swing.JPanel panPieLogin;
    private javax.swing.JPasswordField txtClaveIngresoLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
